import {normalize,normalizeResult,esc,pretty,compareTraces,draftCase} from './v2.js';
const $=s=>document.querySelector(s),state={view:'failures',traces:[],results:[],source:null,candidate:null,health:null,cases:[],job:null,query:''};
const badge=v=>`<span class="badge ${esc(v)}">${esc(v.replaceAll('_',' '))}</span>`;
const traceBy=id=>state.traces.find(t=>t.id===id);
const source=()=>traceBy(state.source)||state.traces[0];
const candidate=()=>traceBy(state.candidate);
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',5000);}
function download(value,name){const u=URL.createObjectURL(new Blob([pretty(value)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function api(path,body){const r=await fetch('/api/v1/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Replay-Token':state.health.session_token,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)}:undefined);const v=await r.json();if(!r.ok)throw Error(v.error?.message||'Request failed');return v;}
function persist(){try{localStorage.setItem('agent-regression-v2',pretty({traces:state.traces.filter(t=>!t.metadata?.synthetic),results:state.results.filter(r=>!r.synthetic)}));}catch{toast('Browser storage is full. Export results to retain them.');}}
function add(t){const checked=normalize(t);if(!state.traces.some(x=>x.id===checked.id))state.traces.push(checked);}
function fail(t){return t.execution.status==='error'||!!t.failures?.length;}
function header(title,sub,buttons=''){return `<div class="page-head"><div><div class="eyebrow">AGENT REGRESSION DEBUGGER</div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${buttons}</div></div>`;}
function render(){
const failures=state.traces.filter(fail),views={failures:failureView,compare:compareView,regressions:regressionView,setup:setupView};
$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#"><span class="brand-mark">↳</span> replay <span class="version">0.3</span></a><div class="eyebrow">WORKSPACE</div><nav class="nav" aria-label="Main navigation">${[['failures','◈','Failures',failures.length],['compare','⇄','Compare',''],['regressions','✓','Regression CI',''],['setup','⌘','Quickstart','']].map(([key,icon,label,n])=>`<button data-view="${key}" class="${state.view===key?'active':''}">${icon} &nbsp; ${label} ${n?`<b>${n}</b>`:''}</button>`).join('')}</nav><div class="sidebar-footer"><div class="connection"><span class="dot"></span>${state.health?'Local runner connected':'Private browser workspace'}</div><p>Keep the evidence.<br>Test the next change.</p><a href="/">Rollout infrastructure ↗</a><a href="/legacy.html">Open step debugger ↗</a><a href="https://github.com/j112929/agent-replay-mvp" target="_blank" rel="noreferrer">Source on GitHub ↗</a></div></aside><main class="main"><div class="topbar"><span>Workspace &nbsp; / &nbsp; <strong>${state.view==='regressions'?'Regression CI':state.view[0].toUpperCase()+state.view.slice(1)}</strong></span><span>${state.health?'LOCAL EXECUTION':'LOCAL DATA · NO UPLOAD'}</span></div><div class="workspace">${state.job?`<div class="pending" role="status">Running registered agent…<button id="cancel">Cancel</button></div>`:''}${views[state.view]()}<div class="footer"><span>Capture → Replay → Diff → Regression CI</span><span>Controlled boundaries. Explicit assertions. Preserved originals.</span></div></div></main></div>`;
document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render();});
document.querySelectorAll('[data-source]').forEach(el=>el.onclick=()=>{state.source=el.dataset.source;render();});
$('#import-btn')?.addEventListener('click',()=>$('#import').click());$('#export')?.addEventListener('click',()=>download(source(),source().id+'.json'));$('#run')?.addEventListener('click',openExperiment);$('#case')?.addEventListener('click',openCase);$('#sync')?.addEventListener('click',sync);$('#export-report')?.addEventListener('click',()=>download(compareTraces(source(),candidate()),'comparison.json'));$('#suite')?.addEventListener('click',openSuite);$('#download-results')?.addEventListener('click',()=>download({results:state.results},'regression-results.json'));$('#cancel')?.addEventListener('click',async()=>{await api('experiments/'+state.job+'/cancel',{});toast('Cancellation requested');});
$('#source-select')?.addEventListener('change',e=>{state.source=e.target.value;render();});$('#candidate-select')?.addEventListener('change',e=>{state.candidate=e.target.value;render();});
$('#search')?.addEventListener('change',e=>{state.query=e.target.value;render();});
document.querySelectorAll('[data-result]').forEach(el=>el.onclick=()=>{const r=state.results[Number(el.dataset.result)];const eligible=state.health&&!r.synthetic&&r.verdict==='pass'&&/^[0-9a-f-]{36}(\.case)?$/.test(r.case_id);const d=dialog('Regression result',`<pre class="result-detail">${esc(pretty(r))}</pre>${eligible?'<button class="primary" id="accept-baseline">Accept as baseline</button>':''}`);d.querySelector('#accept-baseline')?.addEventListener('click',async()=>{try{await api('cases/'+r.case_id.replace(/\.case$/,'')+'/accept',{result_id:r.id});toast('Passing baseline accepted explicitly.');d.close();await sync();}catch(e){d.querySelector('#dialog-error').textContent=e.message;}});});
}
function failureView(){const t=source(),list=state.traces.filter(x=>!x.replay&&x.name.toLowerCase().includes(state.query.toLowerCase()));return header('A failure is a test waiting to happen.','Capture what went wrong. Replay the change. Keep it from coming back.',`${state.health?'<button id="sync">Sync</button>':''}<button id="import-btn">↥ Import JSON</button><button class="primary" data-view="setup">Connect agent ↗</button>`)+`<div class="metrics"><div class="metric"><span>CAPTURED RUNS</span><strong>${state.traces.filter(t=>!t.replay).length}</strong><small>original evidence preserved</small></div><div class="metric"><span>OBSERVED FAILURES</span><strong>${state.traces.filter(fail).length}</strong><small>exceptions + business violations</small></div><div class="metric"><span>REPLAY EXPERIMENTS</span><strong>${state.traces.filter(t=>t.replay).length}</strong><small>isolated candidate executions</small></div><div class="metric"><span>REGRESSION RESULTS</span><strong>${state.results.length}</strong><small>explicit business assertions</small></div></div><div class="panel"><div class="panel-head"><h2>Failure inbox</h2><span class="muted">${state.health?'Local captures':'Synthetic demo + imported runs'}</span></div><div class="runs"><div class="run-list"><div class="search"><input id="search" aria-label="Search captures" placeholder="Search captures…" value="${esc(state.query)}"></div>${list.map(x=>`<button class="run-item ${x.id===t?.id?'selected':''}" data-source="${esc(x.id)}"><strong>${esc(x.name)}</strong><p>${esc(x.id.slice(0,12))} · ${x.steps.length} boundaries</p>${badge(fail(x)?'fail':x.execution.status)} ${x.metadata?.synthetic?badge('synthetic'):''}</button>`).join('')||'<div class="empty">No captures. Import a trace to begin.</div>'}</div><section class="detail">${t?`${badge(fail(t)?'fail':t.execution.status)} ${badge(t.capture_health?.state||'partial')}<h2>${esc(t.name)}</h2><p>${esc(t.failures?.[0]?.message||t.execution.error?.message||'Inspect the captured boundaries and task output.')}</p><div class="notice">${t.metadata?.synthetic?'Synthetic example. No payment or provider API was called.':'Captured completion does not establish business correctness.'}</div><div class="eyebrow">EXECUTION BOUNDARIES</div><div class="timeline">${t.steps.map((s,i)=>step(s,i)).join('')}</div><div class="actions"><button class="primary" id="run">↻ Configure full rerun</button><button data-view="compare">Compare →</button><button id="export">Export</button></div><details><summary>Inputs, environment & capture health</summary><pre class="result-detail">${esc(pretty({input:t.input,provenance:t.provenance,capture_health:t.capture_health}))}</pre></details>`:'<div class="empty">Select a captured run.</div>'}</section></div></div>`;}
function step(s,i,changed=false){return `<div class="step ${changed?'changed':''}"><span class="num">${String(i+1).padStart(2,'0')}</span><div>${esc(s.name)}<small>${esc(s.kind)} · ${esc(s.replay_mode||'captured')}</small></div><span class="timing">${s.execution.status==='error'?badge('error'):Math.round(s.execution.duration_ms)+' ms'}</span></div>`;}
function compareView(){const a=source(),b=candidate();if(!a||!b)return header('Follow the divergence.','Select an original capture and a candidate execution.')+'<div class="panel empty">Import or run a candidate to compare.</div>';const report=compareTraces(a,b),changed=new Set(report.field_changes.map(x=>x.candidate_id));return header('See exactly where the path changed.','Compare inputs, outputs and execution paths. A divergence is evidence, not a root-cause claim.','<button id="export-report">Export diff</button><button class="primary" id="case">Create regression →</button>')+`<div class="compare-top"><div><strong>${report.field_changes.length} changed boundaries · ${report.added_steps.length} added · ${report.removed_steps.length} removed</strong><span>${report.ambiguous_groups.length} ambiguous groups · ${report.coverage.aligned} aligned pairs</span></div><span class="chip">${esc(b.fidelity?.level||'evidence only')}</span></div><div class="grid2">${[[a,'Original capture','source-select'],[b,'Candidate execution','candidate-select']].map(([t,label,id])=>`<section class="panel"><div class="side-heading"><div class="eyebrow">${label}</div><h3>${esc(t.name)}</h3><select id="${id}" aria-label="${label}">${state.traces.map(x=>`<option value="${esc(x.id)}" ${x.id===t.id?'selected':''}>${esc(x.name)} · ${esc(x.id.slice(0,8))}</option>`).join('')}</select><p>${badge(t.execution.status)} ${badge(t.evaluation?.verdict||'not_evaluated')}</p></div><div class="compare-content">${t.steps.map((s,i)=>step(s,i,changed.has(s.id))).join('')}<div class="eyebrow" style="margin-top:20px">TASK OUTPUT</div><pre>${esc(pretty(t.output))}</pre></div></section>`).join('')}</div><section class="panel" style="margin-top:20px"><div class="panel-head"><h2>Boundary changes</h2><span class="muted">inputs · outputs · errors · model</span></div><div class="detail">${report.field_changes.flatMap(pair=>pair.changes.map(r=>`<div class="diff-row"><code>${esc(r.path)}</code><div class="diff-values"><span class="removed">− ${esc(r.before_present?pretty(r.before):'(missing)')}</span><span class="added">+ ${esc(r.after_present?pretty(r.after):'(missing)')}</span></div></div>`)).join('')||'<p>No field changes in aligned boundaries. Review added, removed and ambiguous steps separately.</p>'}</div></section>`;}
function regressionView(){return header('Make the next regression visible.','Business assertions run against candidate code. Historical playback cannot make a test pass.',`<button id="download-results">Export results</button><button class="primary" id="suite" ${state.health?'':'disabled'}>Run registered suite</button>`)+`<div class="story">${[['01 · ORIGINAL FAILURE','fail','299.00','The agent refunded the paid amount instead of the approved amount.'],['02 · FIXED CANDIDATE','pass','29.00','The corrected agent stays within the 30.00 approval limit.'],['03 · BUG REINTRODUCED','fail','299.00','The same assertions catch the regression on the next run.']].map(([title,status,amount,text])=>`<article class="story-card"><div class="eyebrow">${title}</div><h3>Refund policy ${badge(status)}</h3><strong>${amount}</strong><p>${text}</p><span class="badge synthetic">SYNTHETIC · OFFLINE</span></article>`).join('')}</div><div class="panel"><div class="panel-head"><h2>Regression results</h2><span class="muted">fail ≠ error ≠ inconclusive</span></div><table><thead><tr><th>CASE</th><th>VERDICT</th><th>ASSERTIONS</th><th>EVIDENCE</th></tr></thead><tbody>${state.results.map((r,i)=>`<tr><td>${esc(r.case_id)}<br><small class="muted">${r.synthetic?'synthetic example':esc(r.candidate_commit?.slice(0,8)||'local candidate')}</small></td><td>${badge(r.verdict)}</td><td>${r.assertions?.filter(a=>a.verdict==='pass').length||0} / ${r.assertions?.length||0} passed</td><td><button data-result="${i}">Inspect →</button></td></tr>`).join('')}</tbody></table></div><div class="panel" style="margin-top:20px"><div class="panel-head"><h2>Local regression cases</h2></div>${state.cases.length?`<table><tbody>${state.cases.map(c=>`<tr><td>${esc(c.title||c.id)}</td><td>${esc(c.entrypoint_id)}</td><td>${badge(c.baseline?'accepted':'draft')}</td><td>${c.assertions?.length||0} assertions</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Create a case from a comparison to preserve the failure.</div>'}</div><div class="notice">${state.health?'Run registered suites with the local runner. Open a passing local result to explicitly accept its baseline.':'This static workspace displays recorded results. Start the local runner to execute your agent and run CI cases.'}</div>`;}
function setupView(){return header('From one failure to a lasting test.','Python 3.10+ · local-first · explicit instrumentation · no runtime dependencies.','<a class="primary" style="padding:11px 15px;border-radius:7px;text-decoration:none" href="https://agent-replay-debugger.vercel.app/agent-replay-mvp.zip" download>Download SDK ↓</a>')+`<div class="grid2"><div><section class="setup-card"><div class="eyebrow">01 / RUN THE COMPLETE STORY</div><h2>Watch a failure turn into a regression test.</h2><p>The included demo executes broken code, fixed code, and the bug again. It calls no model or payment API.</p><pre class="codebox">python -m pip install -e .
agent-replay demo --directory .replay/demo
agent-replay serve --project .replay/demo/agent-replay.json</pre></section><section class="setup-card"><div class="eyebrow">02 / CAPTURE THE BOUNDARIES</div><h2>Preserve the input, calls and failure.</h2><pre class="codebox">from agent_replay import capture, tool

@tool(boundary_id="orders.lookup")
def lookup(order_id):
    return your_lookup(order_id)

with capture("refund-agent", input=task,
             durability="sync") as run:
    run.set_output(agent(run))</pre><p>Only instrumented boundaries are controlled. Uninstrumented code still runs normally. Journals recover completed evidence after an interrupted process.</p></section></div><div><section class="setup-card"><div class="eyebrow">03 / KEEP THE TEST IN CI</div><h2>Run current code. Assert business outcomes.</h2><pre class="codebox">agent-replay case create failure.json \\
  --entrypoint refund \\
  --output tests/agent_cases/refund.case.json

# Edit the draft with business assertions.
agent-replay test tests/agent_cases \\
  --project agent-replay.json \\
  --report-dir .replay/reports</pre><p>Require the intended action to occur, then check the amount and order. No action is not a successful refund.</p></section><section class="setup-card"><div class="eyebrow">REPLAY GUARANTEES</div><h2>Evidence you can explain.</h2><p>Frozen tools and model outputs. Explicit fixtures for changed inputs. New model or tool versions through registered project configuration. Detached worktrees for code experiments.</p><p>Unmatched or ambiguous calls stop with an inconclusive result. A live model remains nondeterministic. Original traces are preserved.</p><a href="https://github.com/j112929/agent-replay-mvp" target="_blank" rel="noreferrer">Read the implementation and CLI guide ↗</a></section></div></div>`;}
function dialog(title,body,submit){const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2>${body}<div class="actions" style="justify-content:flex-end;margin-top:22px"><button id="close-dialog">Close</button>${submit?'<button class="primary" id="submit-dialog">Continue</button>':''}</div><p id="dialog-error" role="alert"></p>`;document.body.append(d);d.showModal();d.querySelector('#close-dialog').onclick=()=>d.close();d.onclose=()=>d.remove();if(submit)d.querySelector('#submit-dialog').onclick=async()=>{try{await submit(d);}catch(e){d.querySelector('#dialog-error').textContent=e.message;}};return d;}
function openExperiment(){if(!state.health){state.view='setup';render();toast('Use the local runner to execute a registered agent.');return;}const t=source();dialog('Run candidate from the beginning',`<p class="muted">Execute trusted registered code. Frozen boundaries never fall back to real tools.</p><label>Entrypoint<select id="entry">${state.health.entrypoints.map(e=>`<option>${esc(e)}</option>`).join('')}</select></label><label>Replay spec (JSON)<textarea id="spec" rows="14">${esc(pretty({scope:'agent',policy:'frozen',limits:{timeout_seconds:60,max_steps:2000,max_model_calls:0},fixtures:[]}))}</textarea></label><p class="muted">Changed tool inputs require an explicit fixture or registered local tool rule.</p>`,async d=>{const entry=d.querySelector('#entry').value,pre=await api('doctor',{source_id:t.id,entrypoint_id:entry});if(!pre.ready)throw Error(pre.gaps.join('; '));const spec=JSON.parse(d.querySelector('#spec').value);spec.entrypoint_id=entry;const job=await api('experiments',{source_id:t.id,spec});d.close();await watch(job.id);});}
async function watch(id,suite=false){state.job=id;render();try{let job;do{await new Promise(r=>setTimeout(r,600));job=await api((suite?'suites/':'experiments/')+id);}while(['queued','running'].includes(job.state));if(job.result?.trace){add(job.result.trace);state.candidate=job.result.trace.id;state.view='compare';}if(job.result?.results){state.results.push(...job.result.results);state.view='regressions';}if(job.error)toast(job.error);else toast('Execution finished. Inspect its evidence and verdict.');persist();}catch(e){toast(e.message);}finally{state.job=null;render();}}
function openCase(){const t=source(),entry=state.health?.entrypoints?.[0]||'refund';const defaults=[{id:'completed',op:'execution_completed'},{id:'one-refund',select:{boundary_id:'payments.refund'},op:'count',expected:1},{id:'amount-limit',select:{boundary_id:'payments.refund'},path:'/input/value/amount_minor',op:'lte',expected:3000}];dialog('Create a regression case',`<p class="muted">Review these example assertions for your application. Creating a draft does not accept a passing baseline.</p><label>Entrypoint<input id="entry" value="${esc(entry)}"></label><label>Business assertions<textarea id="assertions" rows="13">${esc(pretty(defaults))}</textarea></label><label>Explicit fixtures (optional)<textarea id="fixtures" rows="4">[]</textarea></label>`,async d=>{const assertions=JSON.parse(d.querySelector('#assertions').value),ep=d.querySelector('#entry').value;if(!assertions.length)throw Error('Add a business assertion.');if(state.health){const value=await api('cases',{source_id:t.id,entrypoint_id:ep,assertions,fixtures:JSON.parse(d.querySelector('#fixtures').value)});toast('Draft case saved: '+value.id);}else{download(draftCase(t,ep,assertions),'regression.case.json');toast('Draft exported. Resolve source path and checksum before running.');}d.close();});}
function openSuite(){dialog('Run a registered suite',`<label>Suite<select id="suite-id">${state.health.suites.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label>`,async d=>{const job=await api('suites/run',{registered_suite_id:d.querySelector('#suite-id').value});d.close();await watch(job.id,true);});}
async function sync(){try{let cursor='',count=0;do{const page=await api('traces?limit=100&cursor='+cursor);page.items.forEach(t=>{add(t);count++;});cursor=page.next_cursor;}while(cursor);const results=await api('results');for(const r of results.items){if(!state.results.some(x=>x.id===r.id))state.results.push(normalizeResult(r));}state.cases=(await api('cases')).items;persist();render();toast('Synced '+count+' captures.');}catch(e){toast(e.message);}}
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('Maximum import size is 5 MB.');const data=JSON.parse(await file.text());if(data.results){if(!Array.isArray(data.results)||data.results.length>100)throw Error('Invalid result list');const checked=data.results.map(normalizeResult);state.results.push(...checked);state.view='regressions';}else{const values=Array.isArray(data)?data:[data];if(values.length>100)throw Error('Import at most 100 traces');const checked=values.map(normalize);if(state.health)for(const t of checked)await api('traces/import',{trace:t});checked.forEach(add);state.source=checked[0]?.id;if(checked.length>1)state.candidate=checked[1].id;}persist();render();toast('Imported successfully.');}catch(e){toast(e.message);}finally{e.target.value='';}};
async function init(){try{const cached=JSON.parse(localStorage.getItem('agent-regression-v2')||'{}');(cached.traces||[]).forEach(add);state.results=(cached.results||[]).map(normalizeResult);}catch{}try{const d=await(await fetch('/regression-demo.json')).json();d.traces.forEach(add);state.results.push(...d.results.map(r=>({...r,synthetic:true})));state.source=d.source_id;state.candidate=d.candidate_id;}catch(e){toast('Demo unavailable. Import a trace to begin.');}render();if(['localhost','127.0.0.1'].includes(location.hostname)){try{state.health=await api('health');await sync();}catch{}}}
init();
